enum MemoryType {
  DDR3
  DDR4
  DDR5
}

type Motherboard {
  # image: String
  id: String!
  name: String!
  price: String!
  manufacturer: String!
  partNumber: String!
  componentType: ComponentType!

  socket: String!
  formFactor: String!
  chipset: String!
  memoryMax: String!
  memoryType: MemoryType!
  memorySlots: String!
  color: String!
}

input CreateMotherboardInput {
  id: String!
  name: String!
  price: String!
  manufacturer: String!
  partNumber: String!
  componentType: ComponentType!

  socket: String!
  formFactor: String!
  chipset: String!
  memoryMax: String!
  memoryType: MemoryType!
  memorySlots: String!
  color: String!
}

input UpdateMotherboardInput {
  name: String
  price: String
  manufacturer: String
  partNumber: String
  socket: String
  formFactor: String
  chipset: String
  memoryMax: String
  memoryType: MemoryType
  memorySlots: String
  color: String
}

type Query {
  motherboards: [Motherboard]!
  motherboard(id: String!): Motherboard
}

type Mutation {
  createMotherboard(createMotherboardInput: CreateMotherboardInput!): Boolean
  updateMotherboard(
    id: String!
    updateMotherboardInput: UpdateMotherboardInput!
  ): Boolean
  deleteMotherboard(id: String!): Boolean
}
