type PowerSupply {
  # image: String
  id: String!
  name: String!
  price: String!
  manufacturer: String!
  partNumber: String!
  componentType: ComponentType!

  model: String!
  type: String!
  wattage: String!
  color: String!
  fanless: Boolean!
  SATAConnectors: String!
  length: String!
}

input CreatePowerSupplyInput {
  id: String!
  name: String!
  price: String!
  manufacturer: String!
  partNumber: String!
  componentType: ComponentType!

  model: String!
  type: String!
  wattage: String!
  color: String!
  fanless: Boolean!
  SATAConnectors: String!
  length: String!
}

input UpdatePowerSupplyInput {
  name: String
  price: String
  manufacturer: String
  partNumber: String
  model: String
  type: String
  wattage: String
  color: String
  fanless: Boolean
  SATAConnectors: String
  length: String
}

type Query {
  powerSupplies: [PowerSupply]!
  powerSupply(id: String!): PowerSupply
}

type Mutation {
  createPowerSupply(createPowerSupplyInput: CreatePowerSupplyInput!): Boolean
  updatePowerSupply(
    id: ObjectId!
    updatePowerSupplyInput: UpdatePowerSupplyInput!
  ): Boolean
  deletePowerSupply(id: String!): Boolean
}
