enum StorageType {
  SSD
  HDD
}

type Storage {
  # image: String
  id: String!
  name: String!
  price: String!
  manufacturer: String!
  partNumber: String!
  componentType: ComponentType!

  capacity: String!
  type: StorageType!
  formFactor: String!
  interface: String!
  NVME: Boolean!
}

input CreateStorageInput {
  id: String!
  name: String!
  price: String!
  manufacturer: String!
  partNumber: String!
  componentType: ComponentType!

  capacity: String!
  type: StorageType!
  formFactor: String!
  interface: String!
  NVME: Boolean!
}

input UpdateStorageInput {
  name: String
  price: String
  manufacturer: String
  partNumber: String
  capacity: String
  type: StorageType
  formFactor: String
  interface: String
  NVME: Boolean
}

type Query {
  storages: [Storage]!
  storage(id: String!): Storage
}

type Mutation {
  createStorage(createStorageInput: CreateStorageInput!): Boolean
  updateStorage(id: String!, updateStorageInput: UpdateStorageInput!): Boolean
  deleteStorage(id: String!): Boolean
}
