type VideoCard {
  # image: String
  id: String!
  name: String!
  price: String!
  manufacturer: String!
  partNumber: String!
  componentType: ComponentType!

  model: String!
  chipset: String!
  memory: String!
  memoryType: String!
  coreClock: String!
  interface: String!
  color: String!
  TDP: String!
  coolingFans: String!
  displayPortOutputs: String!
  HDMIOutputs: String!
}

input CreateVideoCardInput {
  id: String!
  name: String!
  price: String!
  manufacturer: String!
  partNumber: String!
  componentType: ComponentType!

  model: String!
  chipset: String!
  memory: String!
  memoryType: String!
  coreClock: String!
  interface: String!
  color: String!
  TDP: String!
  coolingFans: String!
  displayPortOutputs: String!
  HDMIOutputs: String!
}

input UpdateVideoCardInput {
  name: String
  price: String
  manufacturer: String
  partNumber: String
  model: String
  chipset: String
  memory: String
  memoryType: String
  coreClock: String
  interface: String
  color: String
  TDP: String
  coolingFans: String
  displayPortOutputs: String
  HDMIOutputs: String
}

type Query {
  videoCards: [VideoCard]!
  videoCard(id: String!): VideoCard
}

type Mutation {
  createVideoCard(createVideoCardInput: CreateVideoCardInput!): Boolean
  updateVideoCard(
    id: ObjectId!
    updateVideoCardInput: UpdateVideoCardInput!
  ): Boolean
  deleteVideoCard(id: String!): Boolean
}
