name: pcp
networks:
  mongo:
    driver: bridge

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: tmpfs
        target: /data/db
        tmpfs:
          mode: 01777
    ports:
      - 27017:27017
