type Build {
  id: ObjectId!
  name: String!
  user: ObjectId!
  description: String!
  components: Component!
  totalPrice: String!
  dateCreated: Date!
  dateUpdated: Date!
  datePublished: Date
}

input ComponentBuildInput {
  case: String
  cpu: String
  memory: String
  motherboard: String
  powerSupply: String
  storage: String
  videoCard: String
}

input CreateBuildInput {
  id: String!
  name: String!
  user: String!
  description: String
  components: ComponentBuildInput!
  datePublished: Date
}

input UpdateBuildInput {
  user: String!
  name: String
  description: String
  components: ComponentBuildInput
}

type Query {
  getBuilds: [Build]!
  getBuild(id: ObjectId!): Build
}

type Mutation {
  createBuild(createBuildInput: CreateBuildInput!): Boolean
  updateBuild(id: ObjectId!, updateBuildInput: UpdateBuildInput!): Boolean
  deleteBuild(id: ObjectId!): Boolean
}
